#!/usr/bin/env python3
"""Build static city pages from reviewed copy. No runtime/build dependency.

Run: python3 _tools/build-city-pages.py
Content: _tools/city-pages.json. Photos are existing Cook Flooring portfolio
images, not city-specific job claims. Keep the static HTML checked into git.
"""
import html
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE = "https://cookflooring.com"
VERSION = "20260922cities"
CITIES = json.loads((ROOT / "_tools/city-pages.json").read_text())
SERVICES = [
    ("hardwood-floor-installation-ri", "Hardwood installation", "Solid or engineered wood, with board layout, transitions, and trim planned for your rooms.", "Hardwood install"),
    ("floor-refinishing-ri", "Floor refinishing", "An assessment of your existing wood, followed by a sanding and finishing scope suited to its condition.", "Refinish existing floors"),
    ("lvp-installation-ri", "LVP installation", "Luxury vinyl plank with attention to the surface underneath, floor height, and doorway details.", "LVP install"),
    ("bathroom-tile-installation-ri", "Bathroom tile", "Floor, shower, and surround projects with preparation and the areas of work clearly identified.", "Bathroom / tile"),
    ("deck-builder-ri", "Deck building & repair", "A review of your existing deck or proposed project before agreeing on materials, scope, and timing.", "Deck"),
]


def esc(value):
    return html.escape(value, quote=True)


def slug(name):
    return name.lower().replace(" ", "-") + "-ri"


def path(name):
    return "/service-area/" + slug(name) + "/"


def render(city):
    name = city["name"]
    url = SITE + path(name)
    title = f"Flooring & Tile in {name}, RI | Cook Flooring"
    description = f"Need flooring in {name}, RI? Compare hardwood, refinishing, LVP, tile & deck services. Get a free, itemized estimate from Cook Flooring's family crew."
    faqs = city["faqs"] + [
        [f"Is the in-home estimate in {name} free?", "Yes. We offer a free in-home estimate. After reviewing the space and your project, we provide a written, itemized scope so you can see what is included before work begins."],
        ["How do I request a callback?", "Use the form on this page with your name, phone number, town, and project type. You can include a preferred call time. We will contact you about the project and confirm next steps; the requested time is a preference, not a booked appointment. You can also call (401) 602-0958."],
    ]
    schema = {"@context": "https://schema.org", "@graph": [
        {"@type": "WebPage", "@id": url + "#webpage", "url": url, "name": title,
         "description": description, "isPartOf": {"@id": SITE + "/#website"},
         "about": {"@id": url + "#service"}, "breadcrumb": {"@id": url + "#breadcrumb"}},
        {"@type": "Service", "@id": url + "#service", "url": url,
         "name": f"Flooring, tile, and deck services in {name}, Rhode Island",
         "serviceType": [s[1] for s in SERVICES], "provider": {"@id": SITE + "/#business"},
         "areaServed": {"@type": "AdministrativeArea", "name": f"{name}, Rhode Island"}},
        {"@type": "BreadcrumbList", "@id": url + "#breadcrumb", "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": "Home", "item": SITE + "/"},
            {"@type": "ListItem", "position": 2, "name": "Rhode Island service area", "item": SITE + "/service-area/rhode-island/"},
            {"@type": "ListItem", "position": 3, "name": name + ", RI", "item": url}]}]}
    cards = "\n".join(f'''<article class="city-service"><h3><a href="/services/{s}/">{esc(label)}</a></h3><p>{esc(copy)}</p><a class="city-text-link" href="#quote" data-project-choice="{esc(choice)}">Discuss {esc(label.lower())}<span aria-hidden="true"> →</span></a></article>''' for s, label, copy, choice in SERVICES)
    questions = "\n".join(f'<details class="city-faq"><summary>{esc(q)}</summary><p>{esc(a)}</p></details>' for q, a in faqs)
    paragraphs = "\n".join(f"<p>{esc(p)}</p>" for p in city["planning"])
    checklist = "".join(f"<li>{esc(item)}</li>" for item in city["checklist"])
    nearby = "".join(f'<a class="town" href="{path(n)}">{esc(n)}</a>' for n in city["nearby"])
    service_links = "".join(f'<a href="/services/{s}/">{esc(label)}</a>' for s, label, _, _ in SERVICES)
    options = "".join(f"<option>{esc(choice)}</option>" for _, _, _, choice in SERVICES)
    hidden = "".join(f'<input type="hidden" name="{field}" />' for field in ["source_url", "utm_source", "utm_campaign", "utm_medium", "utm_term", "utm_content", "gclid", "gbraid", "wbraid"])
    return f'''<!doctype html>
<!-- Generated by _tools/build-city-pages.py from _tools/city-pages.json. -->
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{esc(title)}</title>
  <meta name="description" content="{esc(description)}" />
  <meta name="robots" content="index, follow, max-image-preview:large" />
  <meta name="theme-color" content="#ffffff" />
  <link rel="canonical" href="{url}" />
  <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
  <meta property="og:type" content="website" />
  <meta property="og:site_name" content="Cook Flooring &amp; Tile" />
  <meta property="og:title" content="{esc(title)}" />
  <meta property="og:description" content="{esc(description)}" />
  <meta property="og:url" content="{url}" />
  <meta property="og:image" content="{SITE}/assets/featured/white-oak-room-progress-960.webp" />
  <meta property="og:image:alt" content="Cook Flooring white oak installation in progress" />
  <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:image:alt" content="Cook Flooring white oak installation in progress" />
    <meta name="twitter:image" content="{SITE}/assets/featured/white-oak-room-progress-960.webp" />
    <meta name="twitter:description" content="{esc(description)}" />
    <meta name="twitter:title" content="{esc(title)}" />
  <link rel="preload" href="/assets/fonts/hepta-slab-latin.woff2" as="font" type="font/woff2" crossorigin />
  <link rel="stylesheet" href="/css/styles.min.css?v={VERSION}" />
  <link rel="preload" href="/assets/fonts/archivo-var-latin.woff2" as="font" type="font/woff2" crossorigin />
    <link rel="stylesheet" href="/css/city-pages.css?v={VERSION}" />
    <link rel="stylesheet" href="/css/stain-board.css?v=20260922m1" />
    <link rel="stylesheet" href="/css/showroom.css?v=20261002" />
  <script src="/js/business-config.js" defer></script>
  <script src="/js/tracking-loader.js?v=20261002" defer></script>
  <script src="/js/lead-tracking.js?v=20260905a" defer></script>
  <script src="/js/quote-form.js?v=20261002" defer></script>
  <script src="/js/city-page.js?v={VERSION}" defer></script>
  <script type="application/ld+json">{json.dumps(schema, indent=2, ensure_ascii=False)}</script>
</head>
<body class="home-page city-page sb">
  <a class="skip-link" href="#main-content">Skip to main content</a>
  <header class="sitehdr is-stuck">
    <a class="brand" href="/" aria-label="Cook Flooring &amp; Tile home"><img class="brand__logo" src="/assets/logo-light.svg" width="170" height="40" alt="" /></a>
    <nav class="sitenav" aria-label="Primary"><a class="nav-hide-sm" href="#services">Services</a><a class="nav-hide-sm" href="#faq">FAQs</a><a class="nav-hide-sm" href="/service-area/rhode-island/">Service area</a><a class="btn-action" href="#quote">Request a callback</a></nav>
  </header>
  <main id="main-content" tabindex="-1">
    <nav class="breadcrumbs wrap" aria-label="Breadcrumb"><a href="/">Home</a><span aria-hidden="true">/</span><a href="/service-area/rhode-island/">Rhode Island</a><span aria-hidden="true">/</span><span aria-current="page">{esc(name)}</span></nav>
    <section class="city-hero">
      <div class="wrap city-hero__grid">
        <div class="city-hero__copy">
          <p class="eyebrow2">Family crew. Written estimates.</p>
          <h1>Flooring &amp; tile in <span>{esc(name)}, RI.</span></h1>
          <p class="city-intro">{esc(city['intro'])}</p>
          <div class="city-actions"><a class="btn-action" href="#quote">Get my free estimate</a><a class="city-call" data-business-call href="tel:+14016020958">Call (401) 602-0958</a></div>
          <p class="city-note">Based in Cranston. Serving {esc(name)} and communities across Rhode Island.</p>
        </div>
        <figure class="city-hero__photo"><img src="/assets/responsive/home-hero-white-oak-800.webp" srcset="/assets/responsive/home-hero-white-oak-480.webp 480w, /assets/responsive/home-hero-white-oak-800.webp 800w" sizes="(max-width: 760px) calc(100vw - 40px), 44vw" width="800" height="1067" alt="White oak flooring from the Cook Flooring project portfolio" fetchpriority="high" decoding="async" /><figcaption>Real Cook Flooring work · White oak installation</figcaption></figure>
      </div>
    </section>
    <div class="city-proof-strip"><div class="wrap"><span>Owner-operated family crew</span><span>Free in-home estimates</span><span>Written, itemized scope</span></div></div>
    <section class="city-section" id="services" aria-labelledby="services-title">
      <div class="wrap"><p class="eyebrow2">Choose your project</p><h2 id="services-title">What can we help with in {esc(name)}?</h2><p class="city-section__intro">Explore the work, then tell us what you have in mind. We will confirm the scope and timing for your home.</p><div class="city-services">{cards}<aside class="city-service city-service--help"><h3>Not sure where to start?</h3><p>Tell us what is worn, what you want to change, and which rooms are involved. A walkthrough helps narrow the options.</p><a class="city-text-link" href="#quote" data-project-choice="Not sure yet">Talk through my options<span aria-hidden="true"> →</span></a></aside></div></div>
    </section>
    <section class="city-section city-section--tint" aria-labelledby="planning-title"><div class="wrap city-planning"><div><p class="eyebrow2">Your {esc(name)} project</p><h2 id="planning-title">{esc(city['focus'])}</h2>{paragraphs}</div><aside class="city-checklist"><h3>Before your walkthrough</h3><ul>{checklist}</ul><a class="city-text-link" href="/guides/flooring-estimate-checklist/">See the full estimate checklist<span aria-hidden="true"> →</span></a></aside></div></section>
    <section class="city-section" aria-labelledby="work-title"><div class="wrap city-work"><figure><img src="/assets/featured/white-oak-hallway-progress-800.webp" width="800" height="1067" alt="Cook Flooring portfolio: white oak boards continuing through a hallway" loading="lazy" decoding="async" /><figcaption>From our project portfolio: a white oak hallway installation.</figcaption></figure><div><p class="eyebrow2">See the workmanship</p><h2 id="work-title">The details carry from room to room.</h2><p>Board direction, doorway transitions, and the finish at the walls all belong in the plan. Browse our real projects and bring the details you like to your walkthrough.</p><a class="city-text-link" href="/#work">View our flooring projects<span aria-hidden="true"> →</span></a></div></div></section>
    <section class="city-section city-section--tint" id="faq" aria-labelledby="faq-title"><div class="wrap city-faq-layout"><div><p class="eyebrow2">Answers before you start</p><h2 id="faq-title">{esc(name)} flooring questions.</h2><p>Have a question about your own rooms? <a href="#quote">Ask for a callback.</a></p></div><div>{questions}</div></div></section>
    <section class="city-section city-quote" id="quote" aria-labelledby="quoteHeading"><div class="wrap city-quote__grid"><div><p class="eyebrow2">Let's talk about your home</p><h2 id="quoteHeading" tabindex="-1">Your {esc(name)} project starts here.</h2><p>Request a callback from the Cook Flooring crew. Tell us about the rooms, the work you need, and a good time to reach you.</p><ol class="city-next"><li>Send your project details.</li><li>We contact you to discuss the work and arrange a walkthrough.</li><li>You receive a written, itemized estimate.</li></ol><a class="city-call" data-business-call href="tel:+14016020958">Call (401) 602-0958</a><p class="city-note">A preferred call time is a request. We will confirm availability with you.</p></div>
      <div class="quote-card" id="quoteCard"><form class="quote-form" id="quoteForm" action="https://formspree.io/f/mgogwyoz" method="POST" data-owner-email="nickbilodeau1150@gmail.com">
        <p class="quote-card__eyebrow">Get a free estimate</p><p class="quote-card__hint">Name, phone, project, and town are required.</p>
        <div class="field row"><div><label for="qName">Name</label><input id="qName" name="name" required autocomplete="name" maxlength="100" /></div><div><label for="qPhone">Phone</label><input id="qPhone" name="phone" type="tel" required autocomplete="tel" inputmode="tel" maxlength="30" /></div></div>
        <div class="field row"><div><label for="qType">Project</label><select id="qType" name="project_type" required><option value="" disabled selected>Choose one</option>{options}<option>Not sure yet</option></select></div><div><label for="qTown">Town and state</label><input id="qTown" name="town" value="{esc(name)}, RI" required autocomplete="address-level2" maxlength="100" /></div></div>
        <div class="field"><label for="qTime">Best time to call <span>(optional)</span></label><select id="qTime" name="preferred_call_time"><option value="">No preference</option><option>Morning, 7 AM–noon</option><option>Afternoon, noon–4 PM</option><option>Late afternoon, 4–6 PM</option></select></div>
        <div class="field"><label for="qEmail">Email <span>(optional)</span></label><input id="qEmail" name="email" type="email" autocomplete="email" maxlength="254" /></div>
        <div class="field"><label for="qDetails">What would you like done? <span>(optional)</span></label><textarea id="qDetails" name="details" maxlength="1200" placeholder="Rooms, rough size, current flooring, and your timing."></textarea></div>
        <input type="hidden" name="request_type" value="Callback and free estimate" /><input type="hidden" name="_subject" value="{esc(name)}, RI: callback and flooring estimate" />{hidden}
        <button class="quote-submit" type="submit">Request my callback</button><p class="quote-status" role="status" aria-live="polite" aria-atomic="true"></p><p class="quote-fineprint">We use your details to contact you about this project. Your request is sent through our website form provider, Formspree.</p><noscript><p>The form still works without JavaScript. Formspree will open to confirm your submission.</p></noscript>
      </form><div class="quote-success" role="status" aria-live="polite" aria-atomic="true" tabindex="-1"><h3>Callback request received.</h3><p>We will contact you to discuss your {esc(name)} project and confirm the next step. Your preferred call time is not a booked appointment.</p><a class="city-call" href="tel:+14016020958">Call (401) 602-0958</a></div></div>
    </div></section>
    <section class="city-section city-nearby" aria-labelledby="nearby-title"><div class="wrap"><h2 id="nearby-title">Also serving nearby communities.</h2><div class="towns">{nearby}<a class="town" href="/service-area/rhode-island/">All service areas</a></div></div></section>
  </main>
  <footer><div class="wrap"><strong>Cook Flooring &amp; Tile</strong><p>Based in Cranston, Rhode Island. Serving {esc(name)}.<br /><a data-business-phone href="tel:+14016020958">(401) 602-0958</a> · <a href="mailto:nickbilodeau1150@gmail.com">Email our crew</a></p><nav class="seo-links" aria-label="Services and homeowner resources">{service_links}<a href="/service-area/rhode-island/">Rhode Island service area</a><a href="/guides/">Flooring guides</a><a href="/guides/flooring-estimate-checklist/">Estimate checklist</a></nav></div></footer>
  <div class="callbar" aria-label="Quick contact"><a class="callbar__call" data-business-call href="tel:+14016020958">Call (401) 602-0958</a><a class="callbar__quote" href="#quote">Request a callback</a></div>
</body>
</html>
'''


if __name__ == "__main__":
    names = {city["name"] for city in CITIES}
    assert len(names) == len(CITIES), "Duplicate city"
    for city in CITIES:
        assert all(n in names for n in city["nearby"])
        output = ROOT / path(city["name"]).lstrip("/") / "index.html"
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(render(city))
    print(f"Built {len(CITIES)} static city pages.")
